apiVersion: v1
clusters:
- cluster:
    server: {{ .PublicK8sAPIServer }}
    certificate-authority-data: {{ .PublicK8sAPIServerRootCA }}
  name: {{ .ClusterName }}
contexts:
- context:
    cluster: {{ .ClusterName }}
    user: {{ .Email }}
  name: {{ .Email }}
current-context: {{ .Email }}
kind: Config
preferences: {}
users:
- name: {{ .Email }}
  user:
    token: {{ .IDToken }}